on:
  schedule:

    - cron:  '30 23 */3 * *'
  workflow_dispatch:
    branches: [main, master]


name: scrape_disaster

jobs:
  render:

    name: scrape_disaster

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgload
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Execute Script
        run: |
          Rscript "inst/scrape_disaster.R"

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add inst/df_disaster.csv
          git commit -F mensagem-comit.txt || echo "No changes to commit"
          git push origin || echo "No changes to commit"
